### ISSUE TITLE
사진 찍다 뻗음. 사진을 못 찾아용

### ISSUE THREAD

**Issue by dubu** [goodroad/android#1]
안드로이드 기기마다 저장소 위치가 다른가 봅니다. 
삼성 S5 인데  사진 위치 못 찾아서 죽어용.. 
실제 위치한 곳은 
/storage/emulated/0/DCIM/Camera/

로그 첨부합니다. 
[goodbug.txt](https://github.com/goodroad/android/files/805875/goodbug.txt)

**Comment by dubu** [comment]
YYYYmmdd 로 바꿔주세용~

params.put("writeDate", String.valueOf(mTime));

**Comment by ghost** [comment]
설정에서 권한 허용해주세요~
어제 apk 올리려다 권한 설정을 안넣어놔서;;;;
오늘 밤엔 수정해서 업데이트 합니다!ㅎㅎ


2017-02-28 15:18 GMT+09:00 DOO-HWAN, KWAK <notifications@github.com>:

**Comment by dubu** [comment]
소스 빌드해서 설치한건데.
앱에 권한 주니까 데이터 들어오네요.
