### ISSUE TITLE
위치기능 비활성화시 안내문구

### ISSUE THREAD

**Issue by el-yun** [goodroad/android#5]
위치기능 비활성화시 안내문구 출력
위치기능이 활성화된 경우 현재위치로 자동으로 지정되는것과 별개로 버튼을 눌러 다시 현위치를 재지정 할수 있으면 좋겠습니다

**Comment by respirer** [comment]
1. 위치 기능 비활성화 시 안내문구(위치 기능이 꺼져있습니다. 지도에서 드래그하여 현재 위치를 선택해주세요.)가 출력이 되도록 해두었는데, 버그가 있어서 안 보이는 현상이 있었네요. 수정해두었습니다.
2. 활성화된 경우에 특정 버튼을 눌러서 현 위치를 지정한다는 말씀이신가요? 아니면 현재 위치 자동 갱신을 의미하시는 것인지요?

**Comment by el-yun** [comment]
1. 확인했습니다
2. 활성화 시킨 후에 현재위치로 지정하고 싶을땐 사진을 다시 찍고와야되는 것같아서 버튼이 있었으면 합니다
