### ISSUE TITLE
앱 이탈 시 Confirm

### ISSUE THREAD

**Issue by el-yun** [goodroad/android#7]
사이클이 단순하다보니 hw백키를 자꾸 누르게 되는데 최초화면에서 back키를 누르면 Confirm으로 종료할것인지 물어봤으면 좋을것같습니다.
기획상에 없던 사항이라 작업공수에 영향을 크게 안준다면 요청드립니다ㅎ

**Comment by respirer** [comment]
수정해두었습니다. 확인 부탁 드립니다.
