### ISSUE TITLE
버전 업 이후 신고하기 버튼 클릭시 팅김

### ISSUE THREAD

**Issue by el-yun** [goodroad/android#8]
버전 업 이후 신고하기 버튼 클릭시 팅김
카톡방처럼 앱 오류 후 팅김

**Comment by el-yun** [comment]
갤럭시S8 , 안드로이드 7.0에서 테스트했습니다.

**Comment by respirer** [comment]
수정 버전 업데이트 해두었습니다.
확인 부탁 드립니다.
