### ISSUE TITLE
단말 - 서버 연동시 파일 저장 오류

### ISSUE THREAD

**Issue by respirer** [goodroad/android#9]
단말 - 서버 연동시 파일 저장 오류가 발생합니다.
며칠에 한번씩 주기적으로 일어나는 현상으로 보아 일시적인 현상은 아닌 것으로 보입니다.

서버로부터 받은 로그입니다.
<!DOCTYPE html>
<html>
<head>
<title>Apache Tomcat/8.5.6 - Error report</title>
<style type="text/css">
H1 {
	font-family: Tahoma, Arial, sans-serif;
	color: white;
	background-color: #525D76;
	font-size: 22px;
}

H2 {
	font-family: Tahoma, Arial, sans-serif;
	color: white;
	background-color: #525D76;
	font-size: 16px;
}

H3 {
	font-family: Tahoma, Arial, sans-serif;
	color: white;
	background-color: #525D76;
	font-size: 14px;
}

BODY {
	font-family: Tahoma, Arial, sans-serif;
	color: black;
	background-color: white;
}

B {
	font-family: Tahoma, Arial, sans-serif;
	color: white;
	background-color: #525D76;
}

P {
	font-family: Tahoma, Arial, sans-serif;
	background: white;
	color: black;
	font-size: 12px;
}

A {
	color: black;
}

A.name {
	color: black;
}

.line {
	height: 1px;
	background-color: #525D76;
	border: none;
}
</style>
</head>
<body>
	<h1>HTTP Status 500 - Request processing failed; nested exception
		is org.springframework.web.multipart.MultipartException: Could not
		parse multipart servlet request; nested exception is
		java.io.IOException: The temporary upload location
		[/tmp/tomcat.4715336693137103739.8080/work/Tomcat/localhost/ROOT/..]
		is not valid</h1>
	<div class="line"></div>
	<p>
		<b>type</b> Exception report
	</p>
	<p>
		<b>message</b> <u>Request processing failed; nested exception is
			org.springframework.web.multipart.MultipartException: Could not parse
			multipart servlet request; nested exception is java.io.IOException:
			The temporary upload location
			[/tmp/tomcat.4715336693137103739.8080/work/Tomcat/localhost/ROOT/..]
			is not valid</u>
	</p>
	<p>
		<b>description</b> <u>The server encountered an internal error
			that prevented it from fulfilling this request.</u>
	</p>
	<p>
		<b>exception</b>
	</p>
	<pre>org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.springframework.web.multipart.MultipartException: Could not parse multipart servlet request; nested exception is java.io.IOException: The temporary upload location [/tmp/tomcat.4715336693137103739.8080/work/Tomcat/localhost/ROOT/..] is not valid
	org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:982)
	org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
	org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:105)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:96)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
	org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
	org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:115)
	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)
	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
	org.springframework.security.web.F

**Comment by respirer** [comment]
오류 진입 방법
1. 앱 실행
2. 신고하기 클릭
3. 사진 촬영
4. 위치 지정
5. 신고하기 클릭

**Comment by dubu** [comment]
tmp folder 지정 java.io.tmpdir

https://github.com/goodroad/rest-api/commit/4241c6aaf25bc931d5c2b9da6f5ffeca5514f3e7
